server:
  port: 8080

spring:
  application:
    name: API-GATEWAY-SERVICE


  cloud:
    gateway:
      routes:
        - id: user-service
#          uri: http://localhost:8081
          uri: http://user-service:8081
          predicates:
            - Path=/api/users/**,/api/vendors/**,/api/auth/**,/api/userservice/**
          filters:
            - StripPrefix=1

        - id: user-service-swagger
#          uri: http://localhost:8081
          uri: http://user-service:8081
          predicates:
            - Path=/userservice/**

        - id: product-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/product/**,/api/bundles/**
          filters:
            - StripPrefix=1


#Exposes actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
debug: true

