server:
  port: 8080

spring:
  application:
    name: API-GATEWAY-SERVICE

#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          secret: ${JWT_SECRET}

  cloud:
    gateway:
      routes:
        - id: user-service
          #uri: http://localhost:8081
          uri: http://user-service:8081
          predicates:
            - Path=/api/users/**,/api/vendors/**,/api/auth/**
          filters:
            - StripPrefix=1



        - id: product-service
          #uri: http://localhost:8082
          uri: http://product-service:8082
          predicates:
            - Path=/api/product/**,/api/bundles/**
          filters:
            - StripPrefix=1



        - id: forecast-service
          uri: http://192.168.0.225:5000
          predicates:
            - Path=/api/forecast/**
          filters:
            - StripPrefix=1

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:63342"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowedHeaders: "*"
            allowCredentials: true

#Exposes actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
debug: true

